schema_version: 20180708
name: greeter-app
version: 0.0.8
runtime: node
build_image: fnproject/node:14-dev
run_image: fnproject/node:14
entrypoint: node func.js
triggers:
- name: greeter-app
  type: http
  source: /greeter-app
