schema_version: 20180708
name: decrypt_f
version: 0.0.19
runtime: python
build_image: fnproject/python:3.9-dev
run_image: fnproject/python:3.9
entrypoint: /python/bin/fdk /function/func.py handler
memory: 256
triggers:
- name: decrypt_f
  type: http
  source: /decrypt_f
