schema_version: 20180708
name: goodbye
version: 0.0.9
runtime: go
build_image: fnproject/go:1.15-dev
run_image: fnproject/go:1.15
entrypoint: ./func
triggers:
- name: goodbye
  type: http
  source: /goodbye
