schema_version: 20180708
name: hello
version: 0.0.4
runtime: go
build_image: fnproject/go:1.15-dev
run_image: fnproject/go:1.15
entrypoint: ./func
triggers:
- name: hello
  type: http
  source: /hello
